(() => {
  const root = document.documentElement;
  const langButton = document.querySelector('#lang');
  const key = 'itundaface-lang';
  const T = {
    en:{phone:{home:'Home',chat:'Chat',identity:'Identity',more:'More',balance:'Available balance',send:'Send',receive:'Receive',pay:'Pay',bills:'Bills',transfer:'Transfer completed',cafe:'Café payment',today:'Today',yesterday:'Yesterday',received:'Payment received',thanks:'Thanks!',verified:'Verified',secure:'Secure access',national:'National ID',marketplace:'Marketplace',discover:'Discover nearby',neighborhood:'Neighborhood',local:'Local services',faceId:'Face ID'},agent:{label:'Agent',float:'Available float',cashIn:'Cash in',cashOut:'Cash out',qr:'QR'},filters:{all:'All',reactions:'Reactions',communication:'Communication',identity:'Identity',finance:'Finance',places:'Places',commerce:'Commerce',state:'State'},glyph:{heart:'Heart',laughing:'Laughing',sad:'Sad','thumbs-up':'Thumbs up',wow:'Wow',chat:'Chat',reply:'Reply',send:'Send',voice:'Voice',notification:'Notification',lock:'Lock',verification:'Verification','id-card':'ID card','face-id':'Face ID','mobile-money':'Mobile money',wallet:'Wallet','bill-payment':'Bill payment',airtime:'Airtime','merchant-payment':'Merchant payment','qr-payment':'QR payment',cafe:'Cafe',restaurant:'Restaurant',market:'Market',hospital:'Hospital',school:'School',supermarket:'Supermarket',gift:'Gift',voucher:'Voucher',package:'Package','shopping-bag':'Shopping bag',success:'Success',verified:'Verified',pending:'Pending',warning:'Warning',error:'Error',locked:'Locked',processing:'Processing',delivered:'Delivered',completed:'Completed'},picker:{heart:'heart',laughing:'laughing','thumbs-up':'thumbs up',wow:'wow',sad:'sad'},a11y:{theme:'Toggle theme',face:'ItundaFace',stage:'3D ItundaFace',reset:'Reset view',spin:'Toggle spin'},hero:['A face for ','every moment.']},
    rw:{phone:{home:'Ahabanza',chat:'Ubutumwa',identity:'Umwirondoro',more:'Ibindi',balance:'Amafaranga ahari',send:'Ohereza',receive:'Akira',pay:'Ishyura',bills:'Inyemezabwishyu',transfer:'Kohereza byarangiye',cafe:'Kwishyura muri café',today:'Uyu munsi',yesterday:'Ejo',received:'Wakiriye amafaranga',thanks:'Murakoze!',verified:'Byagenzuwe',secure:'Kwinjira mu mutekano',national:'Indangamuntu y’u Rwanda',marketplace:'Isoko',discover:'Menya ibiri hafi',neighborhood:'Abaturanyi',local:'Serivisi zo hafi',faceId:'Face ID'},agent:{label:'Umukozi',float:'Amafaranga ahari',cashIn:'Kubitsa',cashOut:'Kubikuza',qr:'QR'},filters:{all:'Byose',reactions:'Ibyiyumvo',communication:'Itumanaho',identity:'Umwirondoro',finance:'Imari',places:'Ahantu',commerce:'Ubucuruzi',state:'Imiterere'},glyph:{heart:'Umutima',laughing:'Guseka',sad:'Agahinda','thumbs-up':'Kumvikanisha',wow:'Gutangara',chat:'Ubutumwa',reply:'Subiza',send:'Ohereza',voice:'Ijwi',notification:'Kumenyesha',lock:'Gufunga',verification:'Kugenzura','id-card':'Indangamuntu','face-id':'Face ID','mobile-money':'Mobile Money',wallet:'Umufuka w’amafaranga','bill-payment':'Kwishyura inyemezabwishyu',airtime:'Airtime','merchant-payment':'Kwishyura umucuruzi','qr-payment':'Kwishyura QR',cafe:'Café',restaurant:'Resitora',market:'Isoko',hospital:'Ibitaro',school:'Ishuri',supermarket:'Supermarket',gift:'Impano',voucher:'Voucher',package:'Paki','shopping-bag':'Agasakoshi k’ubucuruzi',success:'Byagenze neza',verified:'Byagenzuwe',pending:'Birategereje',warning:'Iburira',error:'Ikosa',locked:'Byafunzwe',processing:'Birakorwa',delivered:'Byagejejwe',completed:'Byarangiye'},picker:{heart:'umutima',laughing:'guseka','thumbs-up':'kumvikanisha',wow:'gutangara',sad:'agahinda'},a11y:{theme:'Hindura insanganyamatsiko',face:'ItundaFace',stage:'ItundaFace ya 3D',reset:'Subiza uko byari bimeze',spin:'Tangira cyangwa uhagarike kuzenguruka'},hero:['Isura ya ','buri mwanya.']},
    fr:{phone:{home:'Accueil',chat:'Messages',identity:'Identité',more:'Plus',balance:'Solde disponible',send:'Envoyer',receive:'Recevoir',pay:'Payer',bills:'Factures',transfer:'Transfert terminé',cafe:'Paiement au café',today:'Aujourd’hui',yesterday:'Hier',received:'Paiement reçu',thanks:'Merci !',verified:'Vérifié',secure:'Accès sécurisé',national:'Carte d’identité nationale',marketplace:'Marché',discover:'Découvrir à proximité',neighborhood:'Quartier',local:'Services locaux',faceId:'Face ID'},agent:{label:'Agent',float:'Solde disponible',cashIn:'Dépôt',cashOut:'Retrait',qr:'QR'},filters:{all:'Tout',reactions:'Réactions',communication:'Communication',identity:'Identité',finance:'Finance',places:'Lieux',commerce:'Commerce',state:'États'},glyph:{heart:'Cœur',laughing:'Rire',sad:'Tristesse','thumbs-up':'Pouce levé',wow:'Surprise',chat:'Chat',reply:'Réponse',send:'Envoyer',voice:'Voix',notification:'Notification',lock:'Verrou',verification:'Vérification','id-card':'Carte d’identité','face-id':'Face ID','mobile-money':'Mobile money',wallet:'Portefeuille','bill-payment':'Paiement de facture',airtime:'Crédit mobile','merchant-payment':'Paiement marchand','qr-payment':'Paiement QR',cafe:'Café',restaurant:'Restaurant',market:'Marché',hospital:'Hôpital',school:'École',supermarket:'Supermarché',gift:'Cadeau',voucher:'Bon',package:'Colis','shopping-bag':'Sac shopping',success:'Succès',verified:'Vérifié',pending:'En attente',warning:'Avertissement',error:'Erreur',locked:'Verrouillé',processing:'En cours',delivered:'Livré',completed:'Terminé'},picker:{heart:'cœur',laughing:'rire','thumbs-up':'pouce levé',wow:'surprise',sad:'tristesse'},a11y:{theme:'Changer le thème',face:'ItundaFace',stage:'ItundaFace 3D',reset:'Réinitialiser la vue',spin:'Activer ou désactiver la rotation'},hero:['Un visage pour ','chaque instant.']}
  };
  const lang=()=>{const l=localStorage.getItem(key)||root.lang||'en';return T[l]?l:'en'};
  const setText=(el,v)=>{if(el)el.textContent=v};
  function apply(){
    const l=lang(),t=T[l],p=t.phone;root.lang=l;
    const hero=document.querySelector('h1[data-i18n="hero.title"]');if(hero)hero.innerHTML=t.hero[0]+'<span>'+t.hero[1]+'</span>';
    setText(document.querySelector('#phoneTitle'),p.home);
    const home=document.querySelector('#home');
    if(home){setText(home.querySelector('.balance small'),p.balance);home.querySelectorAll('.balance-actions button').forEach((b,i)=>{const v=[p.send,p.receive,p.pay,p.bills][i];if(v){const n=[...b.childNodes].find(x=>x.nodeType===3);if(n)n.nodeValue=v;else b.append(v)}});const rows=home.querySelectorAll('.row');if(rows[0]){setText(rows[0].querySelector('b'),p.transfer);setText(rows[0].querySelector('div').lastChild,p.today+' · RWF 25,000')}if(rows[1]){setText(rows[1].querySelector('b'),p.cafe);setText(rows[1].querySelector('div').lastChild,p.yesterday+' · RWF 4,500')}}
    const chat=document.querySelector('#chat');if(chat){const rows=chat.querySelectorAll('.row');if(rows[0])setText(rows[0].querySelector('div').lastChild,p.received);if(rows[1])setText(rows[1].querySelector('div').lastChild,p.thanks)}
    const identity=document.querySelector('#identity');if(identity){setText(identity.querySelector('.balance small'),p.identity);setText(identity.querySelector('.balance strong'),p.verified);const rows=identity.querySelectorAll('.row');if(rows[0]){setText(rows[0].querySelector('b'),p.faceId);setText(rows[0].querySelector('div').lastChild,p.secure)}if(rows[1]){setText(rows[1].querySelector('b'),p.national);setText(rows[1].querySelector('div').lastChild,p.verified)}}
    const more=document.querySelector('#more');if(more){const rows=more.querySelectorAll('.row');if(rows[0]){setText(rows[0].querySelector('b'),p.marketplace);setText(rows[0].querySelector('div').lastChild,p.discover)}if(rows[1]){setText(rows[1].querySelector('b'),p.neighborhood);setText(rows[1].querySelector('div').lastChild,p.local)}}
    document.querySelectorAll('.tab').forEach((b,i)=>{const v=[p.home,p.chat,p.identity,p.more][i];if(v){b.dataset.title=v;setText(b.querySelector('span'),v)}});
    const as=document.querySelector('.agent-screen');if(as){setText(as.querySelector('.mini-top span'),t.agent.label);setText(as.querySelector('.agent-balance small'),t.agent.float);as.querySelectorAll('.agent-action').forEach((a,i)=>{const v=[t.agent.cashIn,t.agent.cashOut,t.agent.qr][i],img=a.querySelector('img');a.textContent='';if(img)a.appendChild(img);if(v)a.append(' '+v)})}
    document.querySelectorAll('.filter').forEach(b=>setText(b,t.filters[b.dataset.filter]||b.textContent));
    document.querySelectorAll('.glyph').forEach(card=>{const img=card.querySelector('img'),label=card.querySelector('span');if(!img||!label)return;const name=(img.src.split('/').pop()||'').replace('.svg','');if(t.glyph[name]){setText(label,t.glyph[name]);img.alt=t.glyph[name]}});
    document.querySelectorAll('.pick').forEach(b=>{const raw=b.dataset.faceName;if(raw&&t.picker[raw])setText(b,t.picker[raw])});
    const theme=document.querySelector('#theme');if(theme)theme.setAttribute('aria-label',t.a11y.theme);const hf=document.querySelector('.hero-face');if(hf)hf.alt=t.a11y.face;const sf=document.querySelector('#stageFace');if(sf)sf.alt=t.a11y.stage;const reset=document.querySelector('#reset');if(reset)reset.setAttribute('aria-label',t.a11y.reset);const spin=document.querySelector('#spin');if(spin)spin.setAttribute('aria-label',t.a11y.spin);
  }
  const picker=document.querySelector('#picker');picker?.querySelectorAll('.pick').forEach(b=>{b.dataset.faceName=b.textContent.trim().replace(/\s+/g,'-')});
  if(langButton)langButton.addEventListener('click',()=>setTimeout(apply,0));
  document.querySelector('#filters')?.addEventListener('click',()=>setTimeout(apply,0));
  document.querySelector('#picker')?.addEventListener('click',()=>setTimeout(apply,0));
  if(picker)new MutationObserver(()=>{picker.querySelectorAll('.pick').forEach(b=>{if(!b.dataset.faceName)b.dataset.faceName=b.textContent.trim().replace(/\s+/g,'-')});apply()}).observe(picker,{childList:true});
  const gallery=document.querySelector('#galleryGrid');if(gallery)new MutationObserver(()=>apply()).observe(gallery,{childList:true});
  apply();
})();
